export const FETCH_SEARCH_REPOS_REQUEST = 'FETCH_SEARCH_REPOS_REQUEST';
export const FETCH_SEARCH_REPOS_SUCCESS = 'FETCH_SEARCH_REPOS_SUCCESS';
export const FETCH_SEARCH_REPOS_FAILURE = 'FETCH_SEARCH_REPOS_FAILURE';
